#!/usr/bin/env bash

#Scripts configures an ubuntu server with the requirements below;
#localhost resolves to 127.0.0.2
#facebook.com resolves to 8.8.8.8

cp /etc/hosts /etc/hosts.new
sed -i s/^127.*/"127.0.0.2 localhost"/ hosts.new
echo "8.8.8.8 facebook.com" >> hosts.new
cp hosts.new /etc/hosts
